name: build on github and push to package
on: 
#  push:
#    branches: [ "main"]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: studentproj-api
          dockerfile: gha.Dockerfile
          tags: ghcr.io/olarnr/studentproj/api
          push: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

      - name: Build and push front-end
        uses: docker/build-push-action@v5
        with:
          context: studentproj-fe
          dockerfile: gha.Dockerfile
          tags: ghcr.io/olarnr/studentproj/fe
          push: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
  